# Generated by Django 5.1.2 on 2024-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationdata',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
