# Generated by Django 5.1.2 on 2025-02-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_documentdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentdata',
            name='timestamp',
        ),
    ]
