# Generated by Django 5.1.2 on 2025-02-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_remove_documentdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdata',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentdata',
            name='line_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentdata',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
