# Generated by Django 5.1.2 on 2024-11-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0002_rename_eye_aspect_ratio_avg_eyemetrics_eye_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleEyeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('blink_count', models.IntegerField()),
                ('eye_aspect_ratio', models.FloatField()),
            ],
        ),
    ]
