# Generated by Django 5.1.2 on 2024-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0005_alter_simpleeyemetrics_eye_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='session_id',
            field=models.IntegerField(default=999),
        ),
    ]
