# Generated by Django 5.1.2 on 2024-11-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0005_simpleeyemetrics_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleeyemetrics',
            old_name='session_id',
            new_name='video_id',
        ),
    ]
