# Generated by Django 5.1.2 on 2024-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0005_alter_simpleeyemetrics_eye_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
