# Generated by Django 5.1.2 on 2024-12-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0005_alter_simpleeyemetrics_eye_aspect_ratio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EyeMetrics',
        ),
    ]
