# Generated by Django 5.1.2 on 2024-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0006_delete_eyemetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='x_coordinate_px',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='y_coordinate_px',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
