# Generated by Django 5.1.2 on 2024-11-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0006_rename_session_id_simpleeyemetrics_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='session_id',
            field=models.IntegerField(default=0),
        ),
    ]
