# Generated by Django 5.1.2 on 2024-11-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0007_simpleeyemetrics_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='blink_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='eye_aspect_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='video_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
