# Generated by Django 5.1.2 on 2024-11-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0005_alter_simpleeyemetrics_eye_aspect_ratio'),
        ('eye_processing', '0009_usersession'),
    ]

    operations = [
    ]
