# Generated by Django 5.1.2 on 2024-12-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0006_delete_eyemetrics'),
        ('eye_processing', '0010_merge_20241127_1658'),
    ]

    operations = [
    ]
