# Generated by Django 5.1.2 on 2024-12-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0011_merge_0006_delete_eyemetrics_0010_merge_20241127_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='blink_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='video_id',
            field=models.IntegerField(default=0),
        ),
    ]
