# Generated by Django 5.1.2 on 2024-12-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0007_simpleeyemetrics_x_coordinate_px_and_more'),
        ('eye_processing', '0012_alter_simpleeyemetrics_blink_count_and_more'),
    ]

    operations = [
    ]
