# Generated by Django 5.1.2 on 2024-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0013_merge_20241205_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleeyemetrics',
            name='blink_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
