# Generated by Django 5.1.2 on 2024-12-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0013_merge_20241205_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='blink_count',
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='blink_rate',
            field=models.BooleanField(default=False),
        ),
    ]
