# Generated by Django 5.1.2 on 2025-02-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0014_alter_simpleeyemetrics_blink_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='left_centre',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='no_faces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='normalised_face_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='right_centre',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
