# Generated by Django 5.1.2 on 2025-01-22 12:40

import django.contrib.postgres.fields
import eye_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0014_alter_simpleeyemetrics_blink_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='eye_aspect_ratio',
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='ear_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=eye_processing.models.default_ear_list, null=True, size=None),
        ),
    ]
