# Generated by Django 5.1.2 on 2025-02-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0015_simpleeyemetrics_left_centre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='blink_count',
        ),
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='no_faces',
        ),
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='normalised_face_speed',
        ),
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='x_coordinate_px',
        ),
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='y_coordinate_px',
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='blink_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='face_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='face_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='face_roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='face_yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='focus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='normalised_eye_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
