# Generated by Django 5.1.2 on 2025-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0015_remove_simpleeyemetrics_eye_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='eye_aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
