# Generated by Django 5.1.2 on 2025-02-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0016_remove_simpleeyemetrics_blink_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='gaze_x',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='gaze_y',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
