# Generated by Django 5.1.2 on 2025-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0016_simpleeyemetrics_eye_aspect_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='ear_list',
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='eyes_closed',
            field=models.BooleanField(default=False),
        ),
    ]
