# Generated by Django 5.1.2 on 2025-02-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0017_simpleeyemetrics_gaze_x_simpleeyemetrics_gaze_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='left_iris_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='right_iris_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
