# Generated by Django 5.1.2 on 2025-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0019_simpleeyemetrics_movement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='frame',
            field=models.TextField(blank=True, null=True),
        ),
    ]
