# Generated by Django 5.1.2 on 2025-02-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0020_simpleeyemetrics_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simpleeyemetrics',
            name='frame',
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='wpm',
            field=models.IntegerField(default=0),
        ),
    ]
