# Generated by Django 5.1.2 on 2025-02-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye_processing', '0021_remove_simpleeyemetrics_frame_simpleeyemetrics_wpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='frame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simpleeyemetrics',
            name='reading_mode',
            field=models.IntegerField(default=3),
        ),
    ]
